# Data cleaning

In [1]:
# The code was removed by Watson Studio for sharing.

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [2]:
#data frame shape
df_data_1.shape

(614, 13)

In [3]:
#drop missing values
df_data_1=df_data_1.dropna(axis=0) 

In [4]:
#shape after droping missing values
df_data_1.shape

(480, 13)

# k-Nearest Neighbour

In [5]:
#import libraries
import numpy as np
import matplotlib.pyplot as plt
import numpy as np
from sklearn import preprocessing
%matplotlib inline

In [6]:
df_data_1.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [7]:
#define independent variables
x=df_data_1[['Gender', 'Married', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area']].values

In [8]:
#convert the categorical variables to numeric

le_Gender = preprocessing.LabelEncoder()
le_Gender.fit(['Male','Female'])
x[:,0] = le_Gender.transform(x[:,0]) 

le_Married = preprocessing.LabelEncoder()
le_Married.fit(['Yes','No'])
x[:,1] = le_Married.transform(x[:,1])

le_Education = preprocessing.LabelEncoder()
le_Education.fit(['Graduate','Not Graduate'])
x[:,2] = le_Education.transform(x[:,2])

le_Self_Employed = preprocessing.LabelEncoder()
le_Self_Employed.fit(['Yes','No'])
x[:,3] = le_Self_Employed.transform(x[:,3])

le_Property_Area = preprocessing.LabelEncoder() 
le_Property_Area.fit(['Urban','Rural','Semiurban'])
x[:,9] = le_Property_Area.transform(x[:,9])

x[0:5]

array([[1, 1, 0, 0, 4583, 1508.0, 128.0, 360.0, 1.0, 0],
       [1, 1, 0, 1, 3000, 0.0, 66.0, 360.0, 1.0, 2],
       [1, 1, 1, 0, 2583, 2358.0, 120.0, 360.0, 1.0, 2],
       [1, 0, 0, 0, 6000, 0.0, 141.0, 360.0, 1.0, 2],
       [1, 1, 0, 1, 5417, 4196.0, 267.0, 360.0, 1.0, 2]], dtype=object)

In [9]:
#dependant variable
y = df_data_1['Loan_Status'].values
y[0:5]

array(['N', 'Y', 'Y', 'Y', 'Y'], dtype=object)

In [10]:
#Normalize data
x = preprocessing.StandardScaler().fit(x).transform(x.astype(int))
x[0:5]

array([[ 0.46719815,  0.73716237, -0.50325312, -0.3992747 , -0.13796959,
        -0.02795204, -0.20808917,  0.27554157,  0.41319694, -1.31886834],
       [ 0.46719815,  0.73716237, -0.50325312,  2.50454133, -0.4175358 ,
        -0.604633  , -0.97900085,  0.27554157,  0.41319694,  1.25977445],
       [ 0.46719815,  0.73716237,  1.98707162, -0.3992747 , -0.49118022,
         0.29710022, -0.30756164,  0.27554157,  0.41319694,  1.25977445],
       [ 0.46719815, -1.35655324, -0.50325312, -0.3992747 ,  0.11228014,
        -0.604633  , -0.04644639,  0.27554157,  0.41319694,  1.25977445],
       [ 0.46719815,  0.73716237, -0.50325312,  2.50454133,  0.00931924,
         0.99997795,  1.52024509,  0.27554157,  0.41319694,  1.25977445]])

In [11]:
#Train Test Split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=4)

In [12]:
#classifier
from sklearn.neighbors import KNeighborsClassifier

In [13]:
#get the best k value
from sklearn import metrics
Ks = 10
mean_acc = np.zeros((Ks-1))

for n in range(1,Ks):
    
    #Train Model and Predict  
    neigh = KNeighborsClassifier(n_neighbors = n).fit(x_train,y_train)
    yhat=neigh.predict(x_test)
    mean_acc[n-1] = metrics.accuracy_score(y_test, yhat)

print( "Best accuracy: ", mean_acc.max(), "k=", mean_acc.argmax()+1) 

Best accuracy:  0.7604166666666666 k= 7


In [14]:
#Training
neigh = KNeighborsClassifier(n_neighbors = mean_acc.argmax()+1).fit(x_train,y_train)
neigh

KNeighborsClassifier(n_neighbors=7)

In [15]:
#predicting
yhat = neigh.predict(x_test)
yhat[0:5]

array(['Y', 'Y', 'Y', 'Y', 'Y'], dtype=object)

# Decision Tree

In [16]:
#Modeling
from sklearn.tree import DecisionTreeClassifier
loanTree = DecisionTreeClassifier(criterion="entropy", max_depth = 5,splitter='random')
loanTree

DecisionTreeClassifier(criterion='entropy', max_depth=5, splitter='random')

In [17]:
#Train the model
loanTree.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=5, splitter='random')

In [18]:
#Predict
predTree=loanTree.predict(x_test)


In [19]:
#Evaluation /Accuracy
print("Decision Trees's Accuracy: ", metrics.accuracy_score(y_test, predTree))

Decision Trees's Accuracy:  0.7395833333333334


# Support Vector Machine

In [20]:
#additional libraries
import pylab as pl
import scipy.optimize as opt
from sklearn import svm
from sklearn.metrics import f1_score
from sklearn.metrics import jaccard_score

In [21]:
#Model /Train
clf = svm.SVC(kernel='rbf')
clf.fit(x_train, y_train)


SVC()

In [22]:
#Predict
yhat = clf.predict(x_test)

In [23]:
#Evaluation
#F1 Score
f1_score(y_test, yhat, average='weighted') 

0.7228021978021978

In [24]:
#Jaccard index
jaccard_score(y_test, yhat,pos_label='Y')

0.7073170731707317

# Logistic Regression

In [25]:
#Modeling /Training
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(x_train,y_train)
LR

LogisticRegression(C=0.01, solver='liblinear')

In [26]:
#predict
yhat = LR.predict(x_test)
yhat

array(['Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'N',
       'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'N', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'N', 'Y', 'Y', 'Y', 'Y'], dtype=object)

In [27]:
#Evaluation
#jaccard score
jaccard_score(y_test, yhat,pos_label='Y')

0.7108433734939759

In [28]:
from sklearn.metrics import classification_report, confusion_matrix
print (classification_report(y_test, yhat))

              precision    recall  f1-score   support

           N       0.87      0.37      0.52        35
           Y       0.73      0.97      0.83        61

    accuracy                           0.75        96
   macro avg       0.80      0.67      0.68        96
weighted avg       0.78      0.75      0.72        96



In [29]:
yhat_prob = LR.predict_proba(x_test)
yhat_prob

array([[0.41592549, 0.58407451],
       [0.37317817, 0.62682183],
       [0.32784465, 0.67215535],
       [0.29057224, 0.70942776],
       [0.30958605, 0.69041395],
       [0.37648381, 0.62351619],
       [0.34117181, 0.65882819],
       [0.68344999, 0.31655001],
       [0.40094636, 0.59905364],
       [0.32931564, 0.67068436],
       [0.73273543, 0.26726457],
       [0.38766919, 0.61233081],
       [0.36255789, 0.63744211],
       [0.42617206, 0.57382794],
       [0.32204731, 0.67795269],
       [0.35156333, 0.64843667],
       [0.33344835, 0.66655165],
       [0.35179192, 0.64820808],
       [0.34770961, 0.65229039],
       [0.36182791, 0.63817209],
       [0.72121036, 0.27878964],
       [0.3210639 , 0.6789361 ],
       [0.49424908, 0.50575092],
       [0.41558435, 0.58441565],
       [0.67371202, 0.32628798],
       [0.64431185, 0.35568815],
       [0.68429953, 0.31570047],
       [0.4057178 , 0.5942822 ],
       [0.38209901, 0.61790099],
       [0.34796599, 0.65203401],
       [0.

In [30]:
#log loss
from sklearn.metrics import log_loss
log_loss(y_test, yhat_prob)

0.5747608868889754